# Generated by Django 3.1.2 on 2020-11-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('state', models.IntegerField()),
                ('textbook_picture', models.CharField(max_length=100)),
            ],
        ),
    ]
