# Generated by Django 3.1.2 on 2020-11-20 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('state', models.CharField(choices=[('F', 'For Sale'), ('S', 'Sold'), ('D', 'Draft')], default='F', max_length=1)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('volume_edition', models.IntegerField(blank=True, null=True)),
                ('authors', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
