# Generated by Django 3.1.2 on 2020-11-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textbook',
            old_name='comment',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='textbook',
            name='condition',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='textbook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
