# Generated by Django 3.1.2 on 2020-11-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='textbook_picture',
        ),
        migrations.AddField(
            model_name='textbook',
            name='textbookId',
            field=models.CharField(default='garbage', max_length=26),
        ),
        migrations.AddField(
            model_name='textbook',
            name='textbookPicture',
            field=models.CharField(default='garbage', max_length=100),
        ),
    ]
