# Generated by Django 3.1.2 on 2020-11-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0002_auto_20201102_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='textbookId',
            field=models.CharField(default='temp', max_length=26, unique=True),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='textbookPicture',
            field=models.CharField(default='temp', max_length=100),
        ),
    ]
