# Generated by Django 3.1.3 on 2020-11-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0002_auto_20201111_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
