# Generated by Django 3.1.2 on 2020-11-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0002_auto_20201102_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='price',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='textbookId',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='textbookPicture',
        ),
    ]
