# Generated by Django 3.1.2 on 2020-11-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0002_auto_20201120_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='comments',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
