# Generated by Django 3.1.3 on 2020-11-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0003_textbook_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='state',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
