# Generated by Django 3.1.3 on 2020-11-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0004_auto_20201111_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='state',
            field=models.CharField(choices=[('F', 'For Sale'), ('S', 'Sold'), ('D', 'Draft')], default='F', max_length=1),
        ),
    ]
