# Generated by Django 3.1.3 on 2020-11-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0005_auto_20201111_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='textbookId',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
