# Generated by Django 3.1.3 on 2020-11-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0006_textbook_textbookid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='textbookId',
        ),
    ]
