# Generated by Django 3.1.3 on 2020-11-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0007_remove_textbook_textbookid'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='title',
            field=models.CharField(default='Temp Title', max_length=100),
            preserve_default=False,
        ),
    ]
