# Generated by Django 3.1.3 on 2020-11-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0008_textbook_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='authors',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='textbook',
            name='volume_edition',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
