# Generated by Django 3.1.3 on 2020-11-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0009_auto_20201116_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='volume_edition',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
