# Generated by Django 3.1.2 on 2020-11-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paypal_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
