# Generated by Django 3.1.2 on 2020-11-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_paypal_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='paypal_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
