# Generated by Django 3.1.2 on 2020-11-13 06:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Messages',
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-timestamp']},
        ),
    ]
